//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data_Access_Layer.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conversation
    {
        public int Id { get; set; }
        public Nullable<int> ChatId { get; set; }
        public string Text { get; set; }
        public string Time { get; set; }
        public Nullable<int> UserId { get; set; }
    }
}
